### ISSUE TITLE
Blocking input for all but one top application

### ISSUE THREAD

**Issue by Happy-Ferret** [dannydulai/xl#2]
I know this could potentially compromise security, but is there a way to exclude a single, maximised application from input blocking? 

The idea is to run a small application on top that serves as password indicator (i. e. a textbox displaying asterisks for every entered password character) and could, eventually, offer alternative unlocking methods (a pattern unlocker similar to the ones found on Android/iOS, for example. Should be possible, considering xl already offers a mechanism to change the password -- a pattern would, in the background, be represented by a simple PIN).

**Comment by dannydulai** [comment]
not with xl -- you'd have to get the other "app" to xgrabpointer
